// <auto-generated />
using System;
using HRIncrement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRIncrement.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701100524_AddWorkflowDecisionHistory")]
    partial class AddWorkflowDecisionHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRIncrement.Domain.Entities.EmployeeIncrement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SalaryScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeNumber", "DueDate", "DataSource")
                        .IsUnique();

                    b.ToTable("EmployeeIncrements", (string)null);
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.Gazette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PublishedOn")
                        .HasColumnType("date");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Gazettes", (string)null);
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.SalaryScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("GazetteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MaximumSalary")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("GazetteId", "Code")
                        .IsUnique();

                    b.ToTable("SalaryScales", (string)null);
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.SalaryScalePoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("IncrementAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("PointNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("SalaryScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SalaryScaleId", "PointNumber")
                        .IsUnique();

                    b.ToTable("SalaryScalePoints", (string)null);
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.WorkflowDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeIncrementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DecidedAtUtc");

                    b.HasIndex("EmployeeIncrementId", "DecidedAtUtc");

                    b.ToTable("WorkflowDecisions", (string)null);
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.EmployeeIncrement", b =>
                {
                    b.OwnsOne("HRIncrement.Domain.Entities.IncrementCalculation", "Calculation", b1 =>
                        {
                            b1.Property<Guid>("EmployeeIncrementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("CalculatedAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CalculatedAtUtc");

                            b1.Property<decimal>("ConvertedSalary")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("ConvertedSalary");

                            b1.Property<decimal>("CurrentSalary")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("CurrentSalary");

                            b1.Property<decimal>("IncrementAmount")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("IncrementAmount");

                            b1.Property<decimal>("PayableSalary")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("PayableSalary");

                            b1.Property<int>("SalaryPoint")
                                .HasColumnType("int")
                                .HasColumnName("SalaryPoint");

                            b1.Property<decimal>("StagnationAllowance")
                                .HasPrecision(19, 4)
                                .HasColumnType("decimal(19,4)")
                                .HasColumnName("StagnationAllowance");

                            b1.HasKey("EmployeeIncrementId");

                            b1.ToTable("EmployeeIncrements");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeIncrementId");
                        });

                    b.Navigation("Calculation")
                        .IsRequired();
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.SalaryScale", b =>
                {
                    b.HasOne("HRIncrement.Domain.Entities.Gazette", null)
                        .WithMany("SalaryScales")
                        .HasForeignKey("GazetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.SalaryScalePoint", b =>
                {
                    b.HasOne("HRIncrement.Domain.Entities.SalaryScale", null)
                        .WithMany("Points")
                        .HasForeignKey("SalaryScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.WorkflowDecision", b =>
                {
                    b.HasOne("HRIncrement.Domain.Entities.EmployeeIncrement", null)
                        .WithMany()
                        .HasForeignKey("EmployeeIncrementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.Gazette", b =>
                {
                    b.Navigation("SalaryScales");
                });

            modelBuilder.Entity("HRIncrement.Domain.Entities.SalaryScale", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
