using HRIncrement.Application.DTOs;
using HRIncrement.Application.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HRIncrement.Infrastructure.PdfGeneration;

internal sealed class AssessmentPdfGenerator : IAssessmentPdfGenerator
{
    public byte[] Generate(AssessmentFormDto assessment)
    {
        ArgumentNullException.ThrowIfNull(assessment);

        return Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(40);
            page.DefaultTextStyle(x => x.FontSize(10));
            page.Header().Column(column =>
            {
                column.Item().Text("INCREMENT ASSESSMENT FORM").Bold().FontSize(18).FontColor(Colors.Green.Darken2);
                column.Item().Text($"Gazette: {assessment.GazetteReference}").FontColor(Colors.Grey.Darken1);
            });
            page.Content().PaddingVertical(24).Column(column =>
            {
                AddRow(column, "Employee", $"{assessment.EmployeeName} ({assessment.EmployeeNumber})");
                AddRow(column, "Designation", assessment.Designation);
                AddRow(column, "Grade / Department", $"{assessment.Grade} / {assessment.Department}");
                AddRow(column, "Increment date", assessment.IncrementDate.ToString("dd MMM yyyy"));
                AddRow(column, "Current salary", Currency(assessment.CurrentSalary));
                AddRow(column, "Increment amount", Currency(assessment.IncrementAmount));
                AddRow(column, "Payable salary", Currency(assessment.PayableSalary));
                column.Item().PaddingTop(40).Text("Assessment and approval signatures").Bold();
                column.Item().PaddingTop(35).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
            });
            page.Footer().AlignCenter().Text(text =>
            {
                text.Span("Generated by HR Increment Management System | Page ");
                text.CurrentPageNumber();
            });
        })).GeneratePdf();
    }

    private static void AddRow(ColumnDescriptor column, string label, string value) =>
        column.Item().PaddingVertical(7).Row(row =>
        {
            row.ConstantItem(140).Text(label).SemiBold();
            row.RelativeItem().Text(value);
        });

    private static string Currency(decimal amount) => $"LKR {amount:N2}";
}
